import type { Database } from '@/types/database'

type Job = Database['public']['Tables']['jobs']['Row']
type Article = Database['public']['Tables']['news_articles']['Row']
type Application = Database['public']['Tables']['applications']['Row']

export const mockJobs: Job[] = [
  {
    id: '1',
    title: 'Senior Frontend Developer (ReactJS)',
    slug: 'senior-frontend-developer-reactjs',
    department: 'Engineering',
    location: 'HN',
    employment_type: 'full-time',
    salary_min: 15000000,
    salary_max: 25000000,
    currency: 'VND',
    summary: 'Chúng tôi đang tìm kiếm một Senior Frontend Developer có kinh nghiệm với ReactJS',
    description: '<p>Chúng tôi đang tìm kiếm một Senior Frontend Developer có kinh nghiệm với ReactJS...</p>',
    requirements: '<p>Yêu cầu:</p><ul><li>3+ năm kinh nghiệm với React</li></ul>',
    benefits: '<p>Quyền lợi:</p><ul><li>Lương cạnh tranh</li></ul>',
    skills: ['ReactJS', 'TypeScript', 'Next.js'],
    status: 'published',
    published_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    closed_at: null,
    created_by: null,
    updated_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Bridge System Engineer (BrSE)',
    slug: 'bridge-system-engineer-brse',
    department: 'Engineering',
    location: 'JP',
    employment_type: 'full-time',
    salary_min: 30000000,
    salary_max: 50000000,
    currency: 'VND',
    summary: 'BrSE là cầu nối giữa đội ngũ phát triển và khách hàng Nhật Bản',
    description: '<p>BrSE là cầu nối giữa đội ngũ phát triển và khách hàng Nhật Bản...</p>',
    requirements: '<p>Yêu cầu:</p><ul><li>Tiếng Nhật trình độ N2</li></ul>',
    benefits: '<p>Quyền lợi:</p><ul><li>Lương cao, phúc lợi đầy đủ</li></ul>',
    skills: ['Japanese N2', 'Project Management', 'Communication'],
    status: 'published',
    published_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    closed_at: null,
    created_by: null,
    updated_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Backend Developer (NodeJS/AWS)',
    slug: 'backend-developer-nodejs-aws',
    department: 'Engineering',
    location: 'HCM',
    employment_type: 'full-time',
    salary_min: 12000000,
    salary_max: 20000000,
    currency: 'VND',
    summary: 'Phát triển và duy trì các microservice sử dụng NodeJS và AWS',
    description: '<p>Phát triển và duy trì các microservice sử dụng NodeJS và AWS...</p>',
    requirements: '<p>Yêu cầu:</p><ul><li>2+ năm kinh nghiệm với NodeJS</li></ul>',
    benefits: '<p>Quyền lợi:</p><ul><li>Working remote, bảo hiểm cao cấp</li></ul>',
    skills: ['NodeJS', 'AWS', 'PostgreSQL'],
    status: 'published',
    published_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    closed_at: null,
    created_by: null,
    updated_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'UI/UX Designer',
    slug: 'ui-ux-designer',
    department: 'Design',
    location: 'HN',
    employment_type: 'full-time',
    salary_min: 10000000,
    salary_max: 18000000,
    currency: 'VND',
    summary: 'Thiết kế giao diện người dùng cho các sản phẩm của Fabbi',
    description: '<p>Thiết kế giao diện người dùng cho các sản phẩm của Fabbi...</p>',
    requirements: '<p>Yêu cầu:</p><ul><li>2+ năm kinh nghiệm với Figma</li></ul>',
    benefits: '<p>Quyền lợi:</p><ul><li>Tham gia dự án quốc tế</li></ul>',
    skills: ['Figma', 'UI Design', 'UX Research'],
    status: 'published',
    published_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    closed_at: null,
    created_by: null,
    updated_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'DevOps Engineer',
    slug: 'devops-engineer',
    department: 'Infrastructure',
    location: 'HN',
    employment_type: 'full-time',
    salary_min: 18000000,
    salary_max: 35000000,
    currency: 'VND',
    summary: 'Xây dựng và duy trì hạ tầng CI/CD cho các dự án',
    description: '<p>Xây dựng và duy trì hạ tầng CI/CD cho các dự án...</p>',
    requirements: '<p>Yêu cầu:</p><ul><li>3+ năm kinh nghiệm DevOps</li></ul>',
    benefits: '<p>Quyền lợi:</p><ul><li>Đào tạo chứng chỉ Cloud</li></ul>',
    skills: ['Docker', 'Kubernetes', 'CI/CD'],
    status: 'published',
    published_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    closed_at: null,
    created_by: null,
    updated_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockNews: Article[] = [
  {
    id: '1',
    title: 'Lễ tổng kết Quý 1/2024: Bước đà vững chắc cho những mục tiêu mới',
    slug: 'le-tong-ket-quy-1-2024',
    excerpt: 'Vừa qua, Fabbi đã tổ chức thành công buổi lễ tổng kết Quý 1/2024 với sự tham gia của toàn thể CBNV.',
    body: '<p>Nội dung chi tiết...</p>',
    cover_image_url: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=800',
    category: 'company_events',
    tags: ['event', 'quarterly'],
    status: 'published',
    published_at: '2024-05-15T00:00:00Z',
    author_id: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Fabbi tuyển dụng: Mở rộng đội ngũ kỹ sư phần mềm',
    slug: 'fabbi-tuyen-dung-mo-rong-do-i-ky-su',
    excerpt: 'Fabbi đang tích cực mở rộng đội ngũ với nhiều vị trí kỹ sư phần mềm cấp cao.',
    body: '<p>Nội dung chi tiết...</p>',
    cover_image_url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800',
    category: 'recruitment',
    tags: ['recruitment', 'engineering'],
    status: 'published',
    published_at: '2024-05-10T00:00:00Z',
    author_id: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Cập nhật quy trình phỏng vấn mới tại Fabbi',
    slug: 'cap-nhat-quy-trinh-phong-van-moi',
    excerpt: 'Chúng tôi đã cập nhật quy trình phỏng vấn để đảm bảo trải nghiệm tốt nhất cho ứng viên.',
    body: '<p>Nội dung chi tiết...</p>',
    cover_image_url: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800',
    category: 'recruitment',
    tags: ['recruitment', 'process'],
    status: 'review',
    published_at: null,
    author_id: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'Dự thảo: Kế hoạch team building Quý 2/2024',
    slug: 'du-thao-ke-hoach-team-building-q2',
    excerpt: 'Kế hoạch team building cho Quý 2 đang được xây dựng và sẽ được công bố sớm.',
    body: '<p>Nội dung chi tiết...</p>',
    cover_image_url: 'https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=800',
    category: 'company_events',
    tags: ['team-building', 'draft'],
    status: 'draft',
    published_at: null,
    author_id: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'Báo cáo nội bộ: Phân tích hiệu suất dự án Q1',
    slug: 'bao-cao-noi-bo-phan-tich-hieu-suat-q1',
    excerpt: 'Báo cáo phân tích hiệu suất các dự án trong Quý 1 năm 2024.',
    body: '<p>Nội dung chi tiết...</p>',
    cover_image_url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800',
    category: 'internal',
    tags: ['report', 'performance'],
    status: 'published',
    published_at: '2024-05-05T00:00:00Z',
    author_id: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockApplications: Application[] = [
  {
    id: '1',
    job_id: '1',
    full_name: 'Nguyễn Văn A',
    email: 'nguyenvana@email.com',
    phone: '0123456789',
    portfolio_url: 'https://github.com/example',
    message: 'Tôi rất quan tâm đến vị trí Senior Frontend Developer.',
    cv_file_path: '/uploads/cv/nguyenvana_cv.pdf',
    cv_file_name: 'nguyenvana_cv.pdf',
    cv_file_size: 245760,
    cv_mime_type: 'application/pdf',
    source: 'direct',
    status: 'new',
    submitted_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    job_id: '1',
    full_name: 'Trần Thị B',
    email: 'tranthib@email.com',
    phone: '0987654321',
    portfolio_url: 'https://dribbble.com/tranthib',
    message: 'Với 4 năm kinh nghiệm React, tôi tự tin phù hợp với vị trí này.',
    cv_file_path: '/uploads/cv/tranthib_cv.pdf',
    cv_file_name: 'tranthib_cv.pdf',
    cv_file_size: 312000,
    cv_mime_type: 'application/pdf',
    source: 'linkedin',
    status: 'reviewing',
    submitted_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    job_id: '2',
    full_name: 'Lê Minh C',
    email: 'leminhc@email.com',
    phone: '0369258147',
    portfolio_url: 'https://github.com/leminhc',
    message: 'Tôi có chứng chỉ JLPT N2 và kinh nghiệm làm việc với khách hàng Nhật.',
    cv_file_path: '/uploads/cv/leminhc_cv.pdf',
    cv_file_name: 'leminhc_cv.pdf',
    cv_file_size: 198000,
    cv_mime_type: 'application/pdf',
    source: 'recruitment_agency',
    status: 'shortlisted',
    submitted_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    job_id: '3',
    full_name: 'Phạm Thị D',
    email: 'phamthid@email.com',
    phone: '0741852963',
    portfolio_url: 'https://linkedin.com/in/phamthid',
    message: 'Hơn 3 năm kinh nghiệm với NodeJS và AWS, mong muốn được đóng góp cho Fabbi.',
    cv_file_path: '/uploads/cv/phamthid_cv.pdf',
    cv_file_name: 'phamthid_cv.pdf',
    cv_file_size: 276000,
    cv_mime_type: 'application/pdf',
    source: 'direct',
    status: 'new',
    submitted_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '5',
    job_id: '4',
    full_name: 'Hoàng Văn E',
    email: 'hoangvane@email.com',
    phone: '0852147963',
    portfolio_url: 'https://behance.net/hoangvane',
    message: 'Tôi yêu thích thiết kế UX và có kinh nghiệm với Figma.',
    cv_file_path: '/uploads/cv/hoangvane_cv.pdf',
    cv_file_name: 'hoangvane_cv.pdf',
    cv_file_size: 224000,
    cv_mime_type: 'application/pdf',
    source: 'fabbi_website',
    status: 'rejected',
    submitted_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '6',
    job_id: '1',
    full_name: 'Đặng Thị F',
    email: 'dangthif@email.com',
    phone: '0963218547',
    portfolio_url: 'https://github.com/dangthif',
    message: 'Senior developer với 5 năm kinh nghiệm React/Next.js, sẵn sàng thử thách mới.',
    cv_file_path: '/uploads/cv/dangthif_cv.pdf',
    cv_file_name: 'dangthif_cv.pdf',
    cv_file_size: 335000,
    cv_mime_type: 'application/pdf',
    source: 'referral',
    status: 'reviewing',
    submitted_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
]